# Generated by Django 5.2.4 on 2025-07-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Default value'),
        ),
    ]
