# Generated by Django 5.2.4 on 2025-07-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_parameter_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='output_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Output name'),
        ),
    ]
