# Generated by Django 4.2.4 on 2024-02-22 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(upload_to='resource_pack_file/%Y/%m/%d')),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.CharField(db_index=True, max_length=20, unique=True)),
                ('style', models.CharField(choices=[('dark', 'dark'), ('medium', 'medium'), ('light', 'light'), ('other', 'other')], default='other', max_length=20)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('violet', 'violet'), ('other', 'other')], default='other', max_length=20)),
                ('resolution', models.CharField(choices=[('addon', 'Addon'), ('x8', 'x8'), ('x16', 'x16'), ('x32', 'x32'), ('x64', 'x64'), ('x128', 'x128'), ('x256', 'x256'), ('x512', 'x512'), ('other', 'other')], default='other', max_length=20)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource_pack_img/')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_pack.resourcepack')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_pack.resourcepack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='comments',
            field=models.ManyToManyField(blank=True, to='resource_pack.resourcepackcomment'),
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='downloads_by',
            field=models.ManyToManyField(blank=True, related_name='user_rp_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='image_preview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp', to='resource_pack.resourcepackimage'),
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='images',
            field=models.ManyToManyField(to='resource_pack.resourcepackimage'),
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='likes_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp', to=settings.AUTH_USER_MODEL),
        ),
    ]
