// app/layout.tsx
import type {Metadata} from "next";
import {Geist, Geist_Mono, Nunito, Roboto_Mono} from "next/font/google";
import "./globals.css";
import "../Static/css/base.sass";
import "../Static/css/wide-classes.css";
import "../Static/css/ReactToastify.sass";
import "../Static/css/bootstrap_overwrite.sass";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "../providers";
import LayoutClient from "./LayoutClient";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin", "cyrillic"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${robotoMono.variable}`}
        >
        <body style={{fontFamily: 'var(--font-nunito)'}}>
        <Providers>
            <LayoutClient>{children}</LayoutClient>
        </Providers>
        </body>
        </html>
    );
}
