# Generated by Django 5.1.4 on 2025-01-26 01:20

import adjango.services.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('signup', 'Sign Up'), ('reset_password', 'Reset Password'), ('survey_access', 'Survey Access'), ('auto_created_user', 'Auto Created User')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
