# Generated by Django 5.1.6 on 2025-04-02 23:48

import adjango.fields
import adjango.services.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MINE-DEV', 'Minecraft Developer')], max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=adjango.fields.AManyToManyField(blank=True, related_name='users', to='core.role'),
        ),
    ]
