# Generated by Django 5.0.6 on 2024-05-29 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mode',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'Dark')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
