# Generated by Django 4.2.9 on 2024-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_discorduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='type',
            field=models.CharField(choices=[('SIGN_UP', 'Sign Up'), ('RESET_PASSWORD', 'Reset Password')], max_length=30),
        ),
    ]
