# Generated by Django 5.0.6 on 2024-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_theme_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/theme/background/'),
        ),
    ]
