# Generated by Django 5.2.2 on 2025-07-01 12:36

import phonenumber_field.modelfields
import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_preferred_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='Timezone'),
        ),
    ]
