# Generated by Django 5.2.4 on 2025-07-17 07:01

import adjango.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_user_phone_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('MINE-DEV', 'Minecraft Developer')], max_length=20, unique=True,
                                   verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hw_id',
            field=models.CharField(blank=True, default=None, max_length=600, null=True, verbose_name='Hardware ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=adjango.fields.AManyToManyField(blank=True, related_name='users', to='core.role',
                                                  verbose_name='Roles'),
        ),
    ]
