# Generated by Django 4.2.9 on 2024-03-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_discorduser_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='code',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
