# Generated by Django 5.0.6 on 2024-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_theme_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
