# Generated by Django 5.2.2 on 2025-07-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0003_access_created_at_file_created_at_filetag_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
