# Generated by Django 4.2.9 on 2024-03-03 16:02

import apps.shop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('discount', 'Discount'), ('balance', 'Balance')], max_length=50)),
                ('value', models.IntegerField()),
                ('applys_now', models.IntegerField(default=0)),
                ('applys_max', models.IntegerField(default=60)),
                ('expires_at', models.DateTimeField(default=apps.shop.models.NowPlus30Days)),
            ],
        ),
        migrations.CreateModel(
            name='PromoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=5)),
                ('img', models.ImageField(blank=True, upload_to='images/products')),
                ('discount', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True)),
                ('desc_short', models.CharField(blank=True, max_length=100, null=True)),
                ('review_url', models.CharField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('log_changes', models.TextField(blank=True, null=True)),
                ('test_period_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.file')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hours', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSoftwareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_period_activated', models.BooleanField(default=False, verbose_name='Is tested')),
                ('starts', models.IntegerField(default=0, verbose_name='Starts')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.softwareproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promo')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.softwareproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('priceRub', models.PositiveSmallIntegerField()),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shop.softwareproduct')),
                ('time_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subscriptiontimecategory')),
            ],
        ),
        migrations.AddField(
            model_name='promo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promogroup'),
        ),
        migrations.AddField(
            model_name='promo',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_promo', to=settings.AUTH_USER_MODEL),
        ),
    ]
