# Generated by Django 5.1.4 on 2025-01-26 01:20

import adjango.services.base
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.shop.models
from apps import shop


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='SubscriptionTimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hours', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('discount', 'Discount'), ('balance', 'Balance')], max_length=50)),
                ('value', models.IntegerField()),
                ('applys_now', models.IntegerField(default=0)),
                ('applys_max', models.IntegerField(default=60)),
                ('expires_at', models.DateTimeField(default=apps.shop.models.NowPlus30Days)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_promo', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='shop.promogroup')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=5)),
                ('img', models.ImageField(blank=True, upload_to='images/products')),
                ('discount', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True)),
                ('desc_short', models.CharField(blank=True, max_length=100, null=True)),
                ('review_url', models.CharField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('log_changes', models.TextField(blank=True, null=True)),
                ('test_period_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='core.file')),
            ],
            options={
                'verbose_name_plural': 'Software',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='SoftwareSubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('software', 'Software')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='shop.promo')),
                ('software',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.softwareproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='SoftwareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('software',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                   to='shop.softwareproduct')),
                ('time_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subscriptiontimecategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                models.Model, adjango.services.base.ABaseService,
                shop.services.subscription.SoftwareSubscriptionService),
        ),
        migrations.CreateModel(
            name='UserSoftwareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_period_activated', models.BooleanField(default=False, verbose_name='Is tested')),
                ('starts', models.IntegerField(default=0, verbose_name='Starts')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.softwareproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
