# Generated by Django 4.2.9 on 2024-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeposit',
        ),
    ]
