# Generated by Django 5.0.3 on 2024-03-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_userdeposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareproduct',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Software'},
        ),
    ]
