# Generated by Django 4.2.9 on 2024-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_softwaresubscriptionorder_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaresubscriptionorder',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('software', 'Software')], default='software', max_length=100),
            preserve_default=False,
        ),
    ]
