# Generated by Django 4.2.9 on 2024-03-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_softwaresubscriptionorder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaresubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
