# Generated by Django 4.2.9 on 2024-03-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_softwaresubscription_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaresubscriptionorder',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
