# Generated by Django 5.1.6 on 2025-03-04 08:57

import adjango.services.base
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('html_content', models.TextField(
                    help_text='Используйте HTML для форматирования (цветной, жирный текст, картинки и пр.)',
                    verbose_name='HTML content')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now,
                                                    help_text='Дата и время, когда рассылка должна быть отправлена',
                                                    verbose_name='Start date')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('users', models.ManyToManyField(help_text='Выберите пользователей, которым будет отправлена рассылка',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
