# Generated by Django 5.1.6 on 2025-03-04 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sent_users',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, которым уже было отправлено письмо', related_name='mailings_received', to=settings.AUTH_USER_MODEL, verbose_name='Отправленные пользователи'),
        ),
    ]
