# Generated by Django 5.1.6 on 2025-04-02 23:48

import adjango.services.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='minecraft/launcher/', verbose_name='File')),
                ('version', models.CharField(max_length=500, verbose_name='Version')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256 Hash')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='minecraft/core/', verbose_name='File')),
                ('version', models.CharField(max_length=500, verbose_name='Version')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256 Hash')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
