# Generated by Django 5.1.6 on 2025-04-03 21:59

import adjango.services.base
import django.db.models.deletion
from django.db import migrations, models

import apps.xlmine.services.donate


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0002_initial'),
        ('xlmine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateProduct',
            fields=[
                ('product_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.product')),
            ],
            options={
                'verbose_name': 'Donate',
                'verbose_name_plural': 'Donates',
            },
            bases=('commerce.product',),
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('color', models.CharField(max_length=10, unique=True, verbose_name='Color')),
                ('threshold', models.DecimalField(decimal_places=2,
                                                  help_text='Суммарная сумма донатов, начиная с которой эта привилегия доступна',
                                                  max_digits=10, verbose_name='Donation threshold')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Privilege',
                'verbose_name_plural': 'Privileges',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='DonateOrder',
            fields=[
                ('order_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate_orders',
                                              to='xlmine.donateproduct', verbose_name='Donate product')),
            ],
            options={
                'verbose_name': 'Donate order',
                'verbose_name_plural': 'Donate orders',
            },
            bases=('commerce.order',),
        ),
    ]
