# Generated by Django 5.1.6 on 2025-04-03 22:03

import adjango.services.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_role_user_roles'),
        ('xlmine', '0002_donateproduct_privilege_donateorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXLMine',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('coins', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coins')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
