# Generated by Django 5.1.6 on 2025-04-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
        ('xlmine', '0003_userxlmine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonateProduct',
            new_name='Donate',
        ),
    ]
