# Generated by Django 5.1.6 on 2025-04-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0005_minecraftsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userxlmine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       related_name='xlmine_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
