# Generated by Django 5.1.6 on 2025-04-11 07:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0006_alter_userxlmine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxlmine',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
