# Generated by Django 5.1.6 on 2025-04-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0007_userxlmine_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='code_name',
            field=models.CharField(default='', max_length=100, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='prefix',
            field=models.CharField(default='', max_length=100, verbose_name='Prefix'),
            preserve_default=False,
        ),
    ]
