# Generated by Django 5.1.6 on 2025-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0008_privilege_code_name_privilege_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='security',
            field=models.JSONField(blank=True, null=True, verbose_name='Security manifest'),
        ),
    ]
