# Generated by Django 5.1.6 on 2025-04-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0009_release_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='weight',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='code_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='prefix',
            field=models.CharField(max_length=100, unique=True, verbose_name='Prefix'),
        ),
    ]
