# Generated by Django 5.1.6 on 2025-04-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0010_privilege_weight_alter_privilege_code_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxlmine',
            name='privilege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xlmine_users', to='xlmine.privilege'),
        ),
    ]
