# Generated by Django 5.1.6 on 2025-04-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0012_privilege_gradient_end_privilege_gradient_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='prefix',
            field=models.CharField(max_length=500, unique=True, verbose_name='Prefix'),
        ),
    ]
