# Generated by Django 5.1.6 on 2025-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0013_alter_privilege_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='color',
        ),
        migrations.AlterField(
            model_name='privilege',
            name='prefix',
            field=models.TextField(verbose_name='Prefix'),
        ),
    ]
