# Generated by Django 5.1.6 on 2025-04-18 02:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0015_userxlmine_cape_userxlmine_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userxlmine',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
