# Generated by Django 5.1.6 on 2025-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0016_alter_userxlmine_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='latest_yml',
            field=models.FileField(blank=True, null=True, upload_to='minecraft/launcher/latest_yml/', verbose_name='Latest YML'),
        ),
    ]
