# Generated by Django 5.1.6 on 2025-04-19 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0017_launcher_latest_yml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='latest_yml',
        ),
    ]
