# Generated by Django 5.1.6 on 2025-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xlmine', '0018_remove_launcher_latest_yml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
