# Generated by Django 5.2.4 on 2025-07-17 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmine', '0019_alter_minecraftsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxlmine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
