# Generated by Django 4.2.4 on 2024-02-22 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('PredictNoteAlen', 'Predictnotealen'), ('PredictNoteAlenForListen', 'Predictnotealenforlisten')], default='PredictNoteAlen', max_length=30, verbose_name='Trainer Type')),
                ('desc', models.TextField(blank=True, max_length=400, verbose_name='Description')),
                ('scale_name', models.CharField(choices=[('C', 'C'), ('Cm', 'Cm'), ('C#', 'Csharp'), ('C#m', 'Csharpm'), ('D', 'D'), ('Dm', 'Dm'), ('D#', 'Dsharp'), ('D#m', 'Dsharpm'), ('E', 'E'), ('Em', 'Em'), ('F', 'F'), ('Fm', 'Fm'), ('F#', 'Fsharp'), ('F#m', 'Fsharpm'), ('G', 'G'), ('Gm', 'Gm'), ('G#', 'Gsharp'), ('G#m', 'Gsharpm'), ('A', 'A'), ('Am', 'Am'), ('A#', 'Asharp'), ('A#m', 'Asharpm'), ('B', 'B'), ('Bm', 'Bm'), ('random', 'Random'), ('randomMajor', 'Randommajor'), ('randomMinor', 'Randomminor')], max_length=20, verbose_name='Scale Name')),
                ('scale_octave', models.SmallIntegerField(default=4, verbose_name='Scale Octave')),
                ('degrees', models.JSONField(verbose_name='Degrees')),
                ('chromatic', models.BooleanField(default=False, verbose_name='Chromatic')),
                ('hidden_note_octave', models.SmallIntegerField(default=4, verbose_name='Hidden Note Octave')),
                ('count_questions', models.PositiveSmallIntegerField(default=10, verbose_name='Count Questions')),
                ('cadence_name', models.CharField(choices=[('AuthenticCadence', 'Authenticcadence'), ('PlagalCadence', 'Plagalcadence'), ('DeceptiveCadence', 'Deceptivecadence'), ('HalfCadence', 'Halfcadence'), ('AmenCadence', 'Amencadence'), ('PhrygianHalfCadence', 'Phrygianhalfcadence'), ('BackdoorCadence', 'Backdoorcadence')], default='AuthenticCadence', max_length=100, verbose_name='Cadence Name')),
                ('play_cadence_every_n_question', models.PositiveIntegerField(default=1, verbose_name='Cadence Every N')),
                ('cadence_octave', models.PositiveSmallIntegerField(default=4, verbose_name='Cadence Octave')),
                ('available_replay', models.BooleanField(default=True, verbose_name='Available Replay Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_presets', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPresetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Preset Category')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPresetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer_percentage', models.FloatField(verbose_name='Percentage Right Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='harmony.trainerpreset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainerpreset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.trainerpresetcategory', verbose_name='Category'),
        ),
    ]
