# Generated by Django 5.1.6 on 2025-02-27 06:56

import adjango.services.base
import apps.company.exceptions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('resource_url', models.URLField(blank=True, null=True, verbose_name='Resource url')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК банка')),
                ('current_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('checking_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
            bases=(models.Model, adjango.services.base.ABaseService, apps.company.exceptions.CompanyException),
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='company_documents/', verbose_name='File')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content (Markdown)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company document',
                'verbose_name_plural': 'Companies documents',
            },
            bases=(models.Model, adjango.services.base.ABaseService, apps.company.exceptions.CompanyDocumentException),
        ),
    ]
