# Generated by Django 5.2.2 on 2025-07-01 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'verbose_name': 'Company document', 'verbose_name_plural': 'Company documents'},
        ),
    ]
