# Generated by Django 5.1.6 on 2025-05-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0003_alter_order_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Order amount'),
            preserve_default=False,
        ),
    ]
