# Generated by Django 5.1.6 on 2025-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0004_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True,
                                      verbose_name='Order amount'),
        ),
    ]
