# Generated by Django 5.1.6 on 2025-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('EUR', 'Euro')],
                                   max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(
                choices=[('handmade', 'HandMade'), ('tbank', 'TBank'), ('tbank_installment', 'Tinkoff (Installment)'),
                         ('cloud_payment', 'CloudPayments')], db_index=True, max_length=50, null=True,
                verbose_name='Payment System'),
        ),
    ]
