# Generated by Django 5.1.6 on 2025-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0006_alter_order_amount_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True,
                                   choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('EUR', 'Euro')],
                                   max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('handmade', 'HandMade'), ('tbank', 'TBank'),
                                                        ('tbank_installment', 'Tinkoff (Installment)'),
                                                        ('cloud_payment', 'CloudPayments')], db_index=True,
                                   max_length=50, null=True, verbose_name='Payment System'),
        ),
    ]
