# Generated by Django 5.1.6 on 2025-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0007_alter_order_currency_alter_order_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('EUR', 'Euro')],
                                   default='RUB', max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(
                choices=[('handmade', 'HandMade'), ('tbank', 'TBank'), ('tbank_installment', 'Tinkoff (Installment)'),
                         ('cloud_payment', 'CloudPayments')], db_index=True, default='handmade', max_length=50,
                verbose_name='Payment System'),
            preserve_default=False,
        ),
    ]
