# Generated by Django 5.2.2 on 2025-06-30 20:24

import django.db.models.deletion
from django.db import migrations, models

import apps.commerce.services.balance


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0009_add_freekassa_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePayment',
            fields=[
                ('payment_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.payment')),
            ],
            options={
                'verbose_name': 'Balance payment',
                'verbose_name_plural': 'Balance payments',
            },
            bases=('commerce.payment',),
        ),
        migrations.CreateModel(
            name='BalanceProduct',
            fields=[
                ('product_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.product')),
            ],
            options={
                'verbose_name': 'Balance product',
                'verbose_name_plural': 'Balance products',
            },
            bases=('commerce.product', apps.commerce.services.balance.BalanceProductService),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(
                choices=[('handmade', 'HandMade'), ('tbank', 'TBank'), ('tbank_installment', 'Tinkoff (Installment)'),
                         ('cloud_payment', 'CloudPayments'), ('freekassa', 'FreeKassa'), ('balance', 'Balance')],
                db_index=True, max_length=50, verbose_name='Payment System'),
        ),
        migrations.CreateModel(
            name='BalanceProductOrder',
            fields=[
                ('order_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.order')),
                ('requested_amount',
                 models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Requested amount')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_orders',
                                   to='commerce.balanceproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Balance product order',
                'verbose_name_plural': 'Balance product orders',
            },
            bases=('commerce.order', apps.commerce.services.balance.BalanceProductOrderService),
        ),
    ]
