# Generated by Django 5.2.2 on 2025-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commerce', '0010_balancepayment_balanceproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(
                choices=[('handmade', 'HandMade'), ('tbank', 'TBank'), ('tbank_installment', 'Tinkoff (Installment)'),
                         ('cloud_payment', 'CloudPayments'), ('freekassa', 'FreeKassa'), ('ckassa', 'CKassa'),
                         ('balance', 'Balance')], db_index=True, max_length=50, verbose_name='Payment System'),
        ),
    ]
