# Generated by Django 5.1.6 on 2025-02-27 06:56

import adjango.services.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=10, verbose_name='Mode')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='images/theme/background/', verbose_name='Background Image')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
