# Generated by Django 4.2.9 on 2024-03-23 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_softwaresubscriptionorder_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinkoff', '0002_alter_tinkoffdepositorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkoffdepositorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='tinkoffdepositorder',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promo'),
        ),
        migrations.AlterField(
            model_name='tinkoffdepositorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
