# Generated by Django 4.2.9 on 2024-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff', '0003_remove_tinkoffdepositorder_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkoffdepositorder',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('software', 'Software')], default='deposit', max_length=100),
            preserve_default=False,
        ),
    ]
