# Generated by Django 4.2.9 on 2024-03-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff', '0004_tinkoffdepositorder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinkoffdepositorder',
            old_name='is_paid',
            new_name='is_complete',
        ),
    ]
