# Generated by Django 4.2.9 on 2024-03-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff', '0005_rename_is_paid_tinkoffdepositorder_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinkoffdepositorder',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
