# Generated by Django 5.1.6 on 2025-02-27 06:56

import adjango.services.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.software.services.license
import apps.software.services.software


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('file', models.FileField(upload_to='software/files/', verbose_name='File')),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Software file',
                'verbose_name_plural': 'Software files',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('product_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.product')),
                ('review_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Review URL')),
                ('log_changes', models.TextField(blank=True, null=True)),
                ('test_period_days', models.IntegerField(default=3)),
                ('min_license_order_hours',
                 models.PositiveIntegerField(default=1, help_text='Minimum number of hours to order')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='software.softwarefile', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
            bases=('commerce.product',),
        ),
        migrations.CreateModel(
            name='SoftwareOrder',
            fields=[
                ('order_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.order')),
                ('license_hours', models.PositiveIntegerField(default=1,
                                                              help_text='How many hours of the license are bought by the user',
                                                              verbose_name='License Hours')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                              to='software.software', verbose_name='Software Product')),
            ],
            options={
                'verbose_name': 'Software Order',
                'verbose_name_plural': 'Software Orders',
            },
            bases=('commerce.order',),
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('license_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='License ends at')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses',
                                               to='software.software', verbose_name='Software')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_licenses',
                                   to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Software License',
                'verbose_name_plural': 'Software Licenses',
                'unique_together': {('user', 'software')},
            },
            bases=(
                models.Model, adjango.services.base.ABaseService,
                apps.software.services.license.SoftwareLicenseService),
        ),
    ]
