# Generated by Django 5.1.4 on 2025-01-28 00:54

import adjango.services.base
import apps.commerce.services.order
import apps.software.services.license
import apps.software.services.software
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Software Name')),
                ('review_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Review URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_files', to='core.file', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.product')),
                ('license_hours', models.PositiveIntegerField(default=1, help_text='Сколько часов лицензии выдать', verbose_name='License Hours')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='software.software', verbose_name='Related Software')),
            ],
            options={
                'verbose_name': 'Software Product',
                'verbose_name_plural': 'Software Products',
            },
            bases=('commerce.product', apps.software.services.software.SoftwareProductService),
        ),
        migrations.CreateModel(
            name='SoftwareOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='software.softwareproduct', verbose_name='Software Product')),
            ],
            options={
                'verbose_name': 'Software Order',
                'verbose_name_plural': 'Software Orders',
            },
            bases=('commerce.order', apps.commerce.services.order.IOrderService),
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('license_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='License ends at')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='software.software', verbose_name='Software')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_licenses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Software License',
                'verbose_name_plural': 'Software Licenses',
                'unique_together': {('user', 'software')},
            },
            bases=(models.Model, adjango.services.base.ABaseService, apps.software.services.license.SoftwareLicenseService),
        ),
    ]
