# Generated by Django 5.1.6 on 2025-03-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelicense',
            name='is_tested',
            field=models.BooleanField(default=False, verbose_name='Is tested'),
        ),
    ]
