# Generated by Django 5.1.6 on 2025-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0002_softwarelicense_is_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='guide_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Guide URL'),
        ),
    ]
