# Generated by Django 5.2.4 on 2025-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_wirelessmacro'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelessmacro',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='wireless/'),
        ),
    ]
