# Generated by Django 5.2.4 on 2025-07-13 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0005_wirelessmacro_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wirelessmacro',
            name='icon',
        ),
    ]
