# Generated by Django 4.2.4 on 2024-02-22 03:47

import apps.private_msg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, default=None, null=True)),
                ('file', models.FileField(blank=True, upload_to=apps.private_msg.models.format_private_file_upload)),
                ('voice_msg', models.FileField(blank=True, upload_to=apps.private_msg.models.format_private_file_upload)),
                ('key', models.CharField(default=apps.private_msg.models.GeneratePrivateKey, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_for_del', models.DateTimeField(default=apps.private_msg.models.NowPlusSevenDays)),
            ],
        ),
    ]
