from config.modules.storage import MINIO_USE

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.sites',
    'corsheaders',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'adrf',
    'adjango',
    'channels',
    'django_celery_beat',
    'phonenumber_field',
    'timezone_field',
    'import_export',
    'django_object_actions',
    'silk',
    'endpoints',
    'tinymce',
    'logui',
    'cachalot',
    'csp',

    'apps.seordj',
    'apps.xl_dashboard',
    'apps.company',
    'apps.mailing',
    'apps.confirmation',
    'apps.commerce',
    'apps.redisui',
    'apps.social_oauth',
    'apps.notify',
    'apps.chat',
    'apps.analytics',
    'apps.core',
    'apps.software',
    'apps.tbank',
    'apps.cloudpayments',
    'apps.freekassa',
    'apps.ckassa',
    'apps.theme',
    'apps.surveys',
    'apps.filehost',
    'apps.xlmine',

]
if MINIO_USE: INSTALLED_APPS.append('django_minio_backend')
