# Product
from config.base import DEBUG

DEBUG_SEND_NOTIFIES = False
MINUTES_CONFIRMATION_CODE_EXPIRES = 2
SECONDS_MAX_FREQUENCY_SENDING_CONFIRMATION_CODE = 60
DEBUG_INIT_PAYMENT = True

# Minecraft
HOURS_MINECRAFT_SESSION_LIFETIME = 12 * 24

DEVELOPER_EMAIL = 'ivanhvalevskey@gmail.com'

MAX_DEPOSIT_AMOUNT = 10_000
MIN_DEPOSIT_AMOUNT = 1 if DEBUG else 50
DEFAULT_DEPOSIT_AMOUNT = 100
