# Product
from config.base import DEBUG

DEBUG_SEND_NOTIFIES = False
MINUTES_CONFIRMATION_CODE_EXPIRES = 2
SECONDS_MAX_FREQUENCY_SENDING_CONFIRMATION_CODE = 60
DEBUG_INIT_PAYMENT = True

# Minecraft
HOURS_MINECRAFT_SESSION_LIFETIME = 12 * 24

DEVELOPER_EMAIL = 'ivanhvalevskey@gmail.com'

MAX_DEPOSIT_AMOUNT = 10_000
MIN_DEPOSIT_AMOUNT = 1 if DEBUG else 50
DEFAULT_DEPOSIT_AMOUNT = 100

# Maximum total storage allowed for user file uploads (in bytes)
STORAGE_LIMIT = 300 * 1024 * 1024  # 300 MB

# Converter
MAX_CONVERTER_FILE_SIZE = 50 * 1024 * 1024  # 50 MB
CONVERTER_FILE_RETENTION_DAYS = 60  # 2 months
