from config.base import DOMAIN_URL, env

# Google
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = f'{DOMAIN_URL}/oauth/google/callback/'

# Vk
VK_AUTH_CLIENT_ID = env('VK_AUTH_CLIENT_ID')
VK_AUTH_CLIENT_SECRET = env('VK_AUTH_CLIENT_SECRET')
VK_REDIRECT_URI = f'{DOMAIN_URL}/oauth/vk/callback/'

# Discord
DISCORD_CLIENT_ID = env('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = env('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = f'{DOMAIN_URL}/oauth/discord/callback/'

# Yandex
YANDEX_CLIENT_ID = env('YANDEX_CLIENT_ID')
YANDEX_CLIENT_SECRET = env('YANDEX_CLIENT_SECRET')
YANDEX_REDIRECT_URI = f'{DOMAIN_URL}/oauth/yandex/callback/'

YANDEX_RECAPTCHA_SECRET_KEY = env('YANDEX_RECAPTCHA_SECRET_KEY')

# TBank
TBANK_TERMINAL_KEY = env('TBANK_TERMINAL_KEY')
TBANK_TERMINAL_PASSWORD = env('TBANK_TERMINAL_PASSWORD')

# Cloud Payments
CLOUD_PAYMENT_PUBLIC_ID = env('CLOUD_PAYMENT_PUBLIC_ID')
CLOUD_PAYMENT_PASSWORD = env('CLOUD_PAYMENT_PASSWORD')

# FreeKassa
FK_SECRET_WORD1 = env('FK_SECRET_WORD1')
FK_SECRET_WORD2 = env('FK_SECRET_WORD2')
FK_API_URL = 'https://api.freekassa.ru/v1/'
FK_API_KEY = env('FK_API_KEY')
FK_SHOP_ID = env('FK_MERCHANT_ID')

# CKassa
CKASSA_LOGIN = env('CKASSA_LOGIN')
CKASSA_TOKEN = env('CKASSA_TOKEN')
CKASSA_API_URL = env('CKASSA_API_URL', default='https://api2.ckassa.ru/api-shop/rs/')
CKASSA_SERV_CODE = env('CKASSA_SERV_CODE')

# RCon
RCON_HOST = env('RCON_HOST', '127.0.0.1')
RCON_PORT = int(env('RCON_PORT', '25575'))
RCON_PASSWORD = env('RCON_PASSWORD', 'test123')

# Google captcha
GOOGLE_RECAPTCHA_SECRET_KEY = env('GOOGLE_RECAPTCHA_SECRET_KEY')
GOOGLE_RECAPTCHA_SITE_KEY = env('GOOGLE_RECAPTCHA_SITE_KEY')