XL_DASHBOARD = {
    'General': {
        'Users': 'core.User',
        'Roles': 'core.Role',
        'Files': 'core.File',
        'Theme': 'theme.Theme',
    },
    'Analytics': {
        'Visits': '/xladmin/analytics/visits/',
        'Orders': '/xladmin/analytics/orders/',
        'visits_objs': 'analytics.Visit',
    },
    'xLMine': {
        'User': 'xlmine.UserXLMine',
        'Launcher': 'xlmine.Launcher',
        'Release': 'xlmine.Release',
        'Privilege': 'xlmine.Privilege',
        'MCSession': 'xlmine.MinecraftSession',
        'Console': '/xladmin/rcon_console/',
    },
    'Products': {
        'All': 'commerce.Product',
        'Balance': 'commerce.BalanceProduct',
        'Donate': 'xlmine.Donate',
        'Softwares': 'software.Software',
        'Software Licenses': 'software.SoftwareLicense',
        'Software files': 'software.SoftwareFile',
        'Prices': 'commerce.ProductPrice',
    },
    'Orders': {
        'All': 'commerce.Order',
        'Balance': 'commerce.BalanceProductOrder',
        'Software': 'software.SoftwareOrder',
        'Donate': 'xlmine.DonateOrder',
    },
    'Payments': {
        'All': 'commerce.Payment',
    },
    'Promocode': {
        'Promocode Product Discount': 'commerce.PromocodeProductDiscount',
        'Promocode': 'commerce.Promocode',
        'Promocode Usage': 'commerce.PromocodeUsage',
    },
    'TBank': {
        'TBank Customer': 'tbank.TBankCustomer',
        'TBank Pay': 'tbank.TBankPayment',
        'TBank Recurring Pay': 'tbank.TBankRecurringPayment',
        'TBank Installment': 'tbank.TBankInstallment',
    },
    'Notify': {
        'Notify': 'notify.Notify',
        'Confirmation Code': 'confirmation.ConfirmationCode',
        'Email Confirm. Code': 'confirmation.EmailConfirmationCode',
        'Phone Confirm. Code': 'confirmation.PhoneConfirmationCode',
    },
    'Mailing': {
        'All': 'mailing.Mailing',
    },
    'Commerce': {
        'Client': 'commerce.Client',
        'Employee': 'commerce.Employee',
        'Employee Availability Interval': 'commerce.EmployeeAvailabilityInterval',
        'Employee Leave': 'commerce.EmployeeLeave',
        'GiftCert.': 'commerce.GiftCertificate',
        'GiftCert. Order': 'commerce.GiftCertificateOrder',
        'Gift Cert. Usage': 'commerce.GiftCertificateUsage',
    },
    'Survey': {
        'Survey': 'surveys.Survey',
        'Question': 'surveys.Question',
        'Choice': 'surveys.Choice',
        'Survey Access': 'surveys.SurveyAccess',
        'Survey Attempt': 'surveys.SurveyAttempt',
        'Question Attempt': 'surveys.QuestionAttempt',
    },
    'File host': {
        'Folder': 'filehost.Folder',
        'File': 'filehost.File',
        'Tag': 'filehost.Tag',
        'File Tag': 'filehost.FileTag',
        'Folder Tag': 'filehost.FolderTag',
        'Access': 'filehost.Access',
    },
    'Beat': {
        'Periodic Task': 'django_celery_beat.PeriodicTask',
        'Crontab': 'django_celery_beat.CrontabSchedule',
        'Interval': 'django_celery_beat.IntervalSchedule',
        'Clocked': 'django_celery_beat.ClockedSchedule',
        'Solar': 'django_celery_beat.SolarSchedule',
    },
    'Auth': {
        'Permission': 'auth.Permission',
        'Group': 'auth.Group',
        'Discord User': 'social_oauth.DiscordUser',
        'Google User': 'social_oauth.GoogleUser',
        'VK User': 'social_oauth.VKUser',
        'Yandex User': 'social_oauth.YandexUser',
    },
    'Admin': {
        'Log Entry': 'admin.LogEntry',
        'Content Type': '/xladmin/contenttypes/contenttype/',
        'Django Migrations': 'core.MigrationProxy',
        'Session': 'sessions.Session',
        'Site': 'sites.Site',
        'Token': 'authtoken.Token',
        'TokenProxy': 'authtoken.TokenProxy',
    },
    'Silk': {
        'Request': 'silk.Request',
        'Response': 'silk.Response',
        'SQLQuery': 'silk.SQLQuery',
        'Profile': 'silk.Profile',
    },
    'Company': {
        'Company': 'company.Company',
        'Document': 'company.CompanyDocument',
    },
    'Wireless': {
        'Wireless Macro': 'software.WirelessMacro',
    },
    'Chat': {
        'Room': 'chat.Room',
        'Message': 'chat.Message',
        'File': 'chat.File',
    },
    'xl-actions': {
        'Collect Static': 'run_collectstatic',
    }
}
