# Generated by Django 5.2.2 on 2025-06-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbankinstallment',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Is demo installment available'),
        ),
    ]
