import {makeStyles} from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
    // Primary colors
    primaryMainText: {color: theme.palette.primary.main,},
    primaryLightText: {color: theme.palette.primary.light,},
    primaryDarkText: {color: theme.palette.primary.dark,},
    primaryContrastText: {color: theme.palette.primary.contrastText,},

    // Secondary colors
    secondaryMainText: {color: theme.palette.secondary.main,},
    secondaryLightText: {color: theme.palette.secondary.light,},
    secondaryDarkText: {color: theme.palette.secondary.dark,},

    // Text colors
    textPrimary: {color: theme.palette.text.primary,},
    textPrimary05: {color: theme.palette.text.primary05,},
    textPrimary10: {color: theme.palette.text.primary10,},
    textPrimary15: {color: theme.palette.text.primary15,},
    textPrimary20: {color: theme.palette.text.primary20,},
    textPrimary25: {color: theme.palette.text.primary25,},
    textPrimary30: {color: theme.palette.text.primary30,},
    textPrimary35: {color: theme.palette.text.primary35,},
    textPrimary40: {color: theme.palette.text.primary40,},
    textPrimary45: {color: theme.palette.text.primary45,},
    textPrimary50: {color: theme.palette.text.primary50,},
    textPrimary55: {color: theme.palette.text.primary55,},
    textPrimary60: {color: theme.palette.text.primary60,},
    textPrimary65: {color: theme.palette.text.primary65,},
    textPrimary70: {color: theme.palette.text.primary70,},
    textPrimary75: {color: theme.palette.text.primary75,},
    textPrimary80: {color: theme.palette.text.primary80,},
    textPrimary85: {color: theme.palette.text.primary85,},
    textPrimary90: {color: theme.palette.text.primary90,},
    textPrimary95: {color: theme.palette.text.primary95,},

    textContrast: {color: theme.palette.text.contrast,},
    textContrast05: {color: theme.palette.text.contrast05,},
    textContrast10: {color: theme.palette.text.contrast10,},
    textContrast15: {color: theme.palette.text.contrast15,},
    textContrast20: {color: theme.palette.text.contrast20,},
    textContrast25: {color: theme.palette.text.contrast25,},
    textContrast30: {color: theme.palette.text.contrast30,},
    textContrast35: {color: theme.palette.text.contrast35,},
    textContrast40: {color: theme.palette.text.contrast40,},
    textContrast45: {color: theme.palette.text.contrast45,},
    textContrast50: {color: theme.palette.text.contrast50,},
    textContrast55: {color: theme.palette.text.contrast55,},
    textContrast60: {color: theme.palette.text.contrast60,},
    textContrast65: {color: theme.palette.text.contrast65,},
    textContrast70: {color: theme.palette.text.contrast70,},
    textContrast75: {color: theme.palette.text.contrast75,},
    textContrast80: {color: theme.palette.text.contrast80,},
    textContrast85: {color: theme.palette.text.contrast85,},
    textContrast90: {color: theme.palette.text.contrast90,},
    textContrast95: {color: theme.palette.text.contrast95,},


    textSecondary: {color: theme.palette.text.secondary,},
    textDisabled: {color: theme.palette.text.disabled,},
    textHint: {color: theme.palette.text.hint,},

    // Bg colors
    bgPrimary: {backgroundColor: theme.palette.bg.primary,},
    bgPrimary05: {backgroundColor: theme.palette.bg.primary05,},
    bgPrimary10: {backgroundColor: theme.palette.bg.primary10,},
    bgPrimary15: {backgroundColor: theme.palette.bg.primary15,},
    bgPrimary20: {backgroundColor: theme.palette.bg.primary20,},
    bgPrimary25: {backgroundColor: theme.palette.bg.primary25,},
    bgPrimary30: {backgroundColor: theme.palette.bg.primary30,},
    bgPrimary35: {backgroundColor: theme.palette.bg.primary35,},
    bgPrimary40: {backgroundColor: theme.palette.bg.primary40,},
    bgPrimary45: {backgroundColor: theme.palette.bg.primary45,},
    bgPrimary50: {backgroundColor: theme.palette.bg.primary50,},
    bgPrimary55: {backgroundColor: theme.palette.bg.primary55,},
    bgPrimary60: {backgroundColor: theme.palette.bg.primary60,},
    bgPrimary65: {backgroundColor: theme.palette.bg.primary65,},
    bgPrimary70: {backgroundColor: theme.palette.bg.primary70,},
    bgPrimary75: {backgroundColor: theme.palette.bg.primary75,},
    bgPrimary80: {backgroundColor: theme.palette.bg.primary80,},
    bgPrimary85: {backgroundColor: theme.palette.bg.primary85,},
    bgPrimary90: {backgroundColor: theme.palette.bg.primary90,},
    bgPrimary95: {backgroundColor: theme.palette.bg.primary95,},
    bgSecondary: {backgroundColor: theme.palette.bg.secondary,},
    bgTertiary: {backgroundColor: theme.palette.bg.tertiary,},
    bgQuaternary: {backgroundColor: theme.palette.bg.quaternary,},

    bgContrast: {backgroundColor: theme.palette.bg.contrast,},
    bgContrast05: {backgroundColor: theme.palette.bg.contrast05,},
    bgContrast10: {backgroundColor: theme.palette.bg.contrast10,},
    bgContrast15: {backgroundColor: theme.palette.bg.contrast15,},
    bgContrast20: {backgroundColor: theme.palette.bg.contrast20,},
    bgContrast25: {backgroundColor: theme.palette.bg.contrast25,},
    bgContrast30: {backgroundColor: theme.palette.bg.contrast30,},
    bgContrast35: {backgroundColor: theme.palette.bg.contrast35,},
    bgContrast40: {backgroundColor: theme.palette.bg.contrast40,},
    bgContrast45: {backgroundColor: theme.palette.bg.contrast45,},
    bgContrast50: {backgroundColor: theme.palette.bg.contrast50,},
    bgContrast55: {backgroundColor: theme.palette.bg.contrast55,},
    bgContrast60: {backgroundColor: theme.palette.bg.contrast60,},
    bgContrast65: {backgroundColor: theme.palette.bg.contrast65,},
    bgContrast70: {backgroundColor: theme.palette.bg.contrast70,},
    bgContrast75: {backgroundColor: theme.palette.bg.contrast75,},
    bgContrast80: {backgroundColor: theme.palette.bg.contrast80,},
    bgContrast85: {backgroundColor: theme.palette.bg.contrast85,},
    bgContrast90: {backgroundColor: theme.palette.bg.contrast90,},
    bgContrast95: {backgroundColor: theme.palette.bg.contrast95,},

    bgErrorMain: {backgroundColor: theme.palette.error.main,},

    // BorderColor
    borderPrimary: {borderColor: theme.palette.bg.primary,},
    borderPrimary05: {borderColor: theme.palette.bg.primary05,},
    borderPrimary10: {borderColor: theme.palette.bg.primary10,},
    borderPrimary15: {borderColor: theme.palette.bg.primary15,},
    borderPrimary20: {borderColor: theme.palette.bg.primary20,},
    borderPrimary25: {borderColor: theme.palette.bg.primary25,},
    borderPrimary30: {borderColor: theme.palette.bg.primary30,},
    borderPrimary35: {borderColor: theme.palette.bg.primary35,},
    borderPrimary40: {borderColor: theme.palette.bg.primary40,},
    borderPrimary45: {borderColor: theme.palette.bg.primary45,},
    borderPrimary50: {borderColor: theme.palette.bg.primary50,},
    borderPrimary55: {borderColor: theme.palette.bg.primary55,},
    borderPrimary60: {borderColor: theme.palette.bg.primary60,},
    borderPrimary65: {borderColor: theme.palette.bg.primary65,},
    borderPrimary70: {borderColor: theme.palette.bg.primary70,},
    borderPrimary75: {borderColor: theme.palette.bg.primary75,},
    borderPrimary80: {borderColor: theme.palette.bg.primary80,},
    borderPrimary85: {borderColor: theme.palette.bg.primary85,},
    borderPrimary90: {borderColor: theme.palette.bg.primary90,},
    borderPrimary95: {borderColor: theme.palette.bg.primary95,},

    borderContrast: {borderColor: theme.palette.bg.contrast,},
    borderContrast05: {borderColor: theme.palette.bg.contrast05,},
    borderContrast10: {borderColor: theme.palette.bg.contrast10,},
    borderContrast15: {borderColor: theme.palette.bg.contrast15,},
    borderContrast20: {borderColor: theme.palette.bg.contrast20,},
    borderContrast25: {borderColor: theme.palette.bg.contrast25,},
    borderContrast30: {borderColor: theme.palette.bg.contrast30,},
    borderContrast35: {borderColor: theme.palette.bg.contrast35,},
    borderContrast40: {borderColor: theme.palette.bg.contrast40,},
    borderContrast45: {borderColor: theme.palette.bg.contrast45,},
    borderContrast50: {borderColor: theme.palette.bg.contrast50,},
    borderContrast55: {borderColor: theme.palette.bg.contrast55,},
    borderContrast60: {borderColor: theme.palette.bg.contrast60,},
    borderContrast65: {borderColor: theme.palette.bg.contrast65,},
    borderContrast70: {borderColor: theme.palette.bg.contrast70,},
    borderContrast75: {borderColor: theme.palette.bg.contrast75,},
    borderContrast80: {borderColor: theme.palette.bg.contrast80,},
    borderContrast85: {borderColor: theme.palette.bg.contrast85,},
    borderContrast90: {borderColor: theme.palette.bg.contrast90,},
    borderContrast95: {borderColor: theme.palette.bg.contrast95,},

    borderErrorMain: {borderColor: theme.palette.error.main,},

    // Text Shadow
    textShadowXXSO06: {textShadow: theme.palette.shadow.XXSO06,},
    textShadowXSO06: {textShadow: theme.palette.shadow.XSO06,},
    textShadowSO06: {textShadow: theme.palette.shadow.SO06,},
    textShadowMO06: {textShadow: theme.palette.shadow.MO06,},
    textShadowLO06: {textShadow: theme.palette.shadow.LO06,},
    textShadowXLO06: {textShadow: theme.palette.shadow.XLO06,},
    textShadowXXLO06: {textShadow: theme.palette.shadow.XXLO06,},
    textShadowXXXLO06: {textShadow: theme.palette.shadow.XXXLO06,},

    textShadowXXSO04: {textShadow: theme.palette.shadow.XXSO04,},
    textShadowXSO04: {textShadow: theme.palette.shadow.XSO04,},
    textShadowSO04: {textShadow: theme.palette.shadow.SO04,},
    textShadowMO04: {textShadow: theme.palette.shadow.MO04,},
    textShadowLO04: {textShadow: theme.palette.shadow.LO04,},
    textShadowXLO04: {textShadow: theme.palette.shadow.XLO04,},
    textShadowXXLO04: {textShadow: theme.palette.shadow.XXLO04,},
    textShadowXXXLO04: {textShadow: theme.palette.shadow.XXXLO04,},

    textShadowXXSO02: {textShadow: theme.palette.shadow.XXSO02,},
    textShadowXSO02: {textShadow: theme.palette.shadow.XSO02,},
    textShadowSO02: {textShadow: theme.palette.shadow.SO02,},
    textShadowMO02: {textShadow: theme.palette.shadow.MO02,},
    textShadowLO02: {textShadow: theme.palette.shadow.LO02,},
    textShadowXLO02: {textShadow: theme.palette.shadow.XLO02,},
    textShadowXXLO02: {textShadow: theme.palette.shadow.XXLO02,},
    textShadowXXXLO02: {textShadow: theme.palette.shadow.XXXLO02,},

    // Shadow
    boxShadowXXSO06: {boxShadow: theme.palette.shadow.XXSO06,},
    boxShadowXSO06: {boxShadow: theme.palette.shadow.XSO06,},
    boxShadowSO06: {boxShadow: theme.palette.shadow.SO06,},
    boxShadowMO06: {boxShadow: theme.palette.shadow.MO06,},
    boxShadowLO06: {boxShadow: theme.palette.shadow.LO06,},
    boxShadowXLO06: {boxShadow: theme.palette.shadow.XLO06,},
    boxShadowXXLO06: {boxShadow: theme.palette.shadow.XXLO06,},
    boxShadowXXXLO06: {boxShadow: theme.palette.shadow.XXXLO06,},

    boxShadowXXSO04: {boxShadow: theme.palette.shadow.XXSO04,},
    boxShadowXSO04: {boxShadow: theme.palette.shadow.XSO04,},
    boxShadowSO04: {boxShadow: theme.palette.shadow.SO04,},
    boxShadowMO04: {boxShadow: theme.palette.shadow.MO04,},
    boxShadowLO04: {boxShadow: theme.palette.shadow.LO04,},
    boxShadowXLO04: {boxShadow: theme.palette.shadow.XLO04,},
    boxShadowXXLO04: {boxShadow: theme.palette.shadow.XXLO04,},
    boxShadowXXXLO04: {boxShadow: theme.palette.shadow.XXXLO04,},

    boxShadowXXSO02: {boxShadow: theme.palette.shadow.XXSO02,},
    boxShadowXSO02: {boxShadow: theme.palette.shadow.XSO02,},
    boxShadowSO02: {boxShadow: theme.palette.shadow.SO02,},
    boxShadowMO02: {boxShadow: theme.palette.shadow.MO02,},
    boxShadowLO02: {boxShadow: theme.palette.shadow.LO02,},
    boxShadowXLO02: {boxShadow: theme.palette.shadow.XLO02,},
    boxShadowXXLO02: {boxShadow: theme.palette.shadow.XXLO02,},
    boxShadowXXXLO02: {boxShadow: theme.palette.shadow.XXXLO02,},

    boxShadowXXSI06: {boxShadow: theme.palette.shadow.XXSI06,},
    boxShadowXSI06: {boxShadow: theme.palette.shadow.XSI06,},
    boxShadowSI06: {boxShadow: theme.palette.shadow.SI06,},
    boxShadowMI06: {boxShadow: theme.palette.shadow.MI06,},
    boxShadowLI06: {boxShadow: theme.palette.shadow.LI06,},
    boxShadowXLI06: {boxShadow: theme.palette.shadow.XLI06,},
    boxShadowXXLI06: {boxShadow: theme.palette.shadow.XXLI06,},
    boxShadowXXXLI06: {boxShadow: theme.palette.shadow.XXXLI06,},

    boxShadowXXSI04: {boxShadow: theme.palette.shadow.XXSI04,},
    boxShadowXSI04: {boxShadow: theme.palette.shadow.XSI04,},
    boxShadowSI04: {boxShadow: theme.palette.shadow.SI04,},
    boxShadowMI04: {boxShadow: theme.palette.shadow.MI04,},
    boxShadowLI04: {boxShadow: theme.palette.shadow.LI04,},
    boxShadowXLI04: {boxShadow: theme.palette.shadow.XLI04,},
    boxShadowXXLI04: {boxShadow: theme.palette.shadow.XXLI04,},
    boxShadowXXXLI04: {boxShadow: theme.palette.shadow.XXXLI04,},

    boxShadowXXSI02: {boxShadow: theme.palette.shadow.XXSI02,},
    boxShadowXSI02: {boxShadow: theme.palette.shadow.XSI02,},
    boxShadowSI02: {boxShadow: theme.palette.shadow.SI02,},
    boxShadowMI02: {boxShadow: theme.palette.shadow.MI02,},
    boxShadowLI02: {boxShadow: theme.palette.shadow.LI02,},
    boxShadowXLI02: {boxShadow: theme.palette.shadow.XLI02,},
    boxShadowXXLI02: {boxShadow: theme.palette.shadow.XXLI02,},
    boxShadowXXXLI02: {boxShadow: theme.palette.shadow.XXXLI02,},

    // Error colors
    errorMainText: {color: theme.palette.error.main,},
    errorLightText: {color: theme.palette.error.light,},
    errorDarkText: {color: theme.palette.error.dark,},

    // Warning colors
    warningMainText: {color: theme.palette.warning.main,},
    warningLightText: {color: theme.palette.warning.light,},
    warningDarkText: {color: theme.palette.warning.dark,},

    // Info colors
    infoMainText: {color: theme.palette.info.main,},
    infoLightText: {color: theme.palette.info.light,},
    infoDarkText: {color: theme.palette.info.dark,},

    // Success colors
    successMainText: {color: theme.palette.success.main,},
    successLightText: {color: theme.palette.success.light,},
    successDarkText: {color: theme.palette.success.dark,},
}));
