# Generated by Django 5.1.4 on 2025-01-27 07:22

import adjango.fields
import adjango.services.base
import apps.chat.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/files/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Room name')),
                ('max_participants', models.PositiveSmallIntegerField(default=2, verbose_name='Max participants')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
            bases=(models.Model, adjango.services.base.ABaseService, apps.chat.services.RoomService),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is important')),
                ('files', adjango.fields.AManyToManyField(blank=True, related_name='messages', to='chat.file', verbose_name='Files')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
            bases=(models.Model, adjango.services.base.ABaseService),
        ),
    ]
