// react-icons
import {
    SiAdobeaftereffects,
    SiAdobeaudition,
    SiAdobeillustrator,
    SiAdobephotoshop,
    SiAdobepremierepro,
    SiBootstrap,
    SiC,
    SiCmake,
    SiCplusplus,
    SiCss3,
    SiDjango,
    SiDocker,
    SiElectron,
    SiFastapi,
    SiFigma,
    SiFlask,
    SiGit,
    SiGnubash,
    SiGradle,
    SiHtml5,
    SiIntellijidea,
    SiJquery,
    SiLinux,
    SiMui,
    SiMysql,
    SiNeovim,
    SiNginx,
    SiObsidian,
    SiOpencv,
    SiPostgresql,
    SiPostman,
    SiPycharm,
    SiPython,
    SiPytorch,
    SiQt,
    SiRabbitmq,
    SiReact,
    SiRedis,
    SiRedux,
    SiSass,
    SiSelenium,
    SiSpring,
    SiSqlite,
    SiSublimetext,
    SiTypescript,
    SiVuedotjs,
} from 'react-icons/si';
import {DiJava, DiVisualstudio} from 'react-icons/di';
import {Skill} from "Modules/DevResume/types";

/* ─────────── Список технологий с индивидуальными параметрами ─────────── */
export const skills: Skill[] = [
    {name: 'Python', Icon: SiPython, color: '#4faeff'},
    {name: 'TypeScript', Icon: SiTypescript, color: '#3293ff'},
    {name: 'C', Icon: SiC, color: '#555555'},
    {name: 'C++', Icon: SiCplusplus, color: '#0095ff'},
    {name: 'Java', Icon: DiJava, color: '#ED8B00', scale: 1.3},
    {name: 'Sass', Icon: SiSass, color: '#ff6ab6'},
    {name: 'HTML5', Icon: SiHtml5, color: '#E34F26'},
    {name: 'CSS3', Icon: SiCss3, color: '#2a9df1'},
    {name: 'Django', Icon: SiDjango, color: '#23bb65'},
    {name: 'React', Icon: SiReact, color: '#61DAFB'},
    {name: 'Vue', Icon: SiVuedotjs, color: '#41B883'},
    {name: 'Redux', Icon: SiRedux, color: '#764ABC'},
    {name: 'Material UI', Icon: SiMui, color: '#007FFF'},
    {name: 'FastAPI', Icon: SiFastapi, color: '#009688'},
    {name: 'Flask', Icon: SiFlask, color: '#ff5757', scale: 1},
    {name: 'Qt', Icon: SiQt, color: '#41CD52'},
    {name: 'Spring', Icon: SiSpring, color: '#6DB33F'},
    {name: 'Electron', Icon: SiElectron, color: '#2bc4de'},
    {name: 'Bootstrap', Icon: SiBootstrap, color: '#7952B3'},
    {name: 'Gradle', Icon: SiGradle, color: '#017b77', scale: 1.1},
    {name: 'RabbitMQ', Icon: SiRabbitmq, color: '#FF6600'},
    {name: 'Docker', Icon: SiDocker, color: '#2496ED', scale: 1.1},
    {name: 'Nginx', Icon: SiNginx, color: '#009639'},
    {name: 'Selenium', Icon: SiSelenium, color: '#43B02A'},
    {name: 'Git', Icon: SiGit, color: '#F05032'},
    {name: 'Linux', Icon: SiLinux, color: '#FCC624'},
    {name: 'Bash', Icon: SiGnubash, color: '#4EAA25'},
    {name: 'CMake', Icon: SiCmake, color: '#064F8C'},
    {name: 'OpenCV', Icon: SiOpencv, color: '#5C3EE8'},
    {name: 'PyTorch', Icon: SiPytorch, color: '#EE4C2C'},
    {name: 'jQuery', Icon: SiJquery, color: '#0769AD'},
    {name: 'Redis', Icon: SiRedis, color: '#DC382D'},
    {name: 'SQLite', Icon: SiSqlite, color: '#00618e'},
    {name: 'PostgreSQL', Icon: SiPostgresql, color: '#336791'},
    {name: 'MySQL', Icon: SiMysql, color: '#4479A1', scale: 1.4},
    {name: 'PyCharm', Icon: SiPycharm, color: '#75ad49'},
    {name: 'Intellij IDEA', Icon: SiIntellijidea, color: '#902a46'},
    {name: 'VS Code', Icon: DiVisualstudio, color: '#3d7ba8', scale: 1.3},
    {name: 'Neovim', Icon: SiNeovim, color: '#57A143'},
    {name: 'Postman', Icon: SiPostman, color: '#FF6C37'},
    {name: 'Figma', Icon: SiFigma, color: '#F24E1E'},
    {name: 'After Effects', Icon: SiAdobeaftereffects, color: '#9999FF'},
    {name: 'Premiere Pro', Icon: SiAdobepremierepro, color: '#9999FF'},
    {name: 'Audition', Icon: SiAdobeaudition, color: '#00C8FF'},
    {name: 'Photoshop', Icon: SiAdobephotoshop, color: '#00C8FF'},
    {name: 'Illustrator', Icon: SiAdobeillustrator, color: '#FF9A00'},
    {name: 'Obsidian', Icon: SiObsidian, color: '#675BFF'},
    {name: 'Sublime', Icon: SiSublimetext, color: '#FF9800'},
];