# Generated by Django 5.1.6 on 2025-02-27 06:56

import adjango.services.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.notify.services.notify


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(db_index=True, max_length=50, verbose_name='Notify type')),
                ('status',
                 models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Send error')],
                                  db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('scheduled_time', models.DateTimeField(db_index=True, verbose_name='Scheduled sent time')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='Sent time')),
                ('context', models.JSONField(default=dict, verbose_name='Context')),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notify',
                'verbose_name_plural': 'Notifies',
                'ordering': ['-scheduled_time'],
                'indexes': [models.Index(fields=['status', 'scheduled_time'], name='notify_noti_status_4c0840_idx')],
            },
            bases=(models.Model, adjango.services.base.ABaseService, apps.notify.services.notify.NotifyService),
        ),
    ]
