# Generated by Django 5.2.2 on 2025-06-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commerce', '0009_add_freekassa_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeKassaPayment',
            fields=[
                ('payment_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='commerce.payment')),
                ('fk_order_id', models.BigIntegerField(blank=True, null=True, verbose_name='FreeKassa order ID')),
                ('order_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Order hash')),
                ('status',
                 models.IntegerField(choices=[(0, 'New'), (1, 'Paid'), (6, 'Refund'), (8, 'Error'), (9, 'Cancel')],
                                     db_index=True, default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'FreeKassa payment',
                'verbose_name_plural': 'FreeKassa payments',
            },
            bases=('commerce.payment',),
        ),
    ]
